### ISSUE TITLE
Error on Registering 

### ISSUE THREAD

**Issue by m2ura** [jsdecena/laracom#11]
Hello, I get 500 Internal Server Error when trying to register on your live Laracom.
I haven't tried it on my localhost though.

Question... How would you implement Electronic Fund Payment, that when a client adds a product into a cart, instead of going to stripe payment. It just generates Payment code like #234561234. And a bank name, with the amount to be transfered?

**Comment by jsdecena** [comment]
Hi. I would create a separate module for that. When the user checks out on that payment method, it just creates the order but still pending status. Then your payment gateway **may** have an API to call back your app and if the payment is transferred, then you update the status of the order and commence shipping the item. If you need help on the module, we can talk about it more. Let me know.

**Comment by m2ura** [comment]
Something like this, when a client has been redirected to checkout it shows the store bank details with the random string for payment reference for the client.

![screenshot_2018-02-01-12-31-16](https://user-images.githubusercontent.com/13012135/35676003-d740d45c-0752-11e8-94c5-207ae5ee6e7b.png)

**Comment by m2ura** [comment]
And then when a client has made the transfer to the store bank account, he/she just click on the button to notify the store that the payment has been done. 

![screenshot_2018-02-01-12-31-20](https://user-images.githubusercontent.com/13012135/35676175-76a8b9d8-0753-11e8-9a69-c8a42d232585.png)

**Comment by m2ura** [comment]
Each user when registering must get their random unique string for payment reference.

**Comment by jsdecena** [comment]
This looks like another third-party gateway or a bank transfer module. Definitely, you can create one like that.
