### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by hermas-natenju** [jsdecena/laracom#12]
Hi everyone
After installing on Wamp php 7.0

![image](https://user-images.githubusercontent.com/16770882/36213736-c9da75de-11a7-11e8-9755-b9cd66e8ef16.png)

please help!

**Comment by jsdecena** [comment]
@hermas-natenju Wamp, Xampp or Mamp is not advisable to work on a laravel project. Please use either Homestead (vagrant) or Docker.
