### ISSUE TITLE
Product quantity/inventory 

### ISSUE THREAD

**Issue by michael-hampton** [jsdecena/laracom#153]
There doesn’t seem to be any checks in the code that checks the available product quantity. This means that a user can still add items to the cart which have 0 quantity meaning you are selling something you don’t have. What should happen is that if the quantity is 0 then an out of stock message should be displayed. You could even have some sort of functions that will email the customer when the product becomes available.

**Comment by michael-hampton** [comment]
That would be great if you could share it

**Comment by marpal71** [comment]
The feature would be really helpful.

  Regards

**Comment by hectonpdomingos** [comment]
I agree. Also, if the user put a string on it, the app breaks at least in the demo version. (screenshot  below)
https://ibb.co/0ftb7tF
