### ISSUE TITLE
Product Image alone not getting stored inside the products folders.

### ISSUE THREAD

**Issue by vignesh-subash** [jsdecena/laracom#17]
Hi i am trying to uploading some new items along with images in product section. Cover photo alone not getting stored in product folder but instead of that its getting stored inside XAMPP folder. At the same time image of the product are correctly stored inside the product folder.yeah i know u ll suggest me to try using homestead but im giving demo to college students through goDaddy shared hosting so kindly help me out.

**Comment by jsdecena** [comment]
Hi @vignesh-subash Can you pull the latest master branch? I have made a few fix to it. You also need to run `php artisan storage:link` to make a symlink on the `storage` folder to the `public` If you will not do that, the images will not be seen as public. 

It is really not advisable to host your Laravel application in a shared hosting environment. [DigitalOcean](https://m.do.co/c/bce94237de96) has $5/mo where you can set up a LEMP environment and run this app.
