### ISSUE TITLE
paypal

### ISSUE THREAD

**Issue by tsulavi** [jsdecena/laracom#18]
hello,

how to configure paypal sandbox to test it from my localhost (http://localhost)?

i have an error

> App \ Shop \ PaymentMethods \ Paypal \ Exceptions \ PaypalRequestError {"error":"invalid_client","error_description":"Client Authentication failed"}

**Comment by jsdecena** [comment]
@tsulavi you have to go in the admin and configure the paypal credentials in the payment methods 😉
