### ISSUE TITLE
feature request: direct checkout

### ISSUE THREAD

**Issue by badgeek** [jsdecena/laracom#19]
congrats for laracom, from the code it looks neat and clean, btw possible to add direct checkout feature?

**Comment by jsdecena** [comment]
@badgeek Yup. Good idea :) I just need to find time to work on it and will let you know

**Comment by muffaddal** [comment]
Does Direct Checkout refer to Cash on Delivery (COD), may be i can take this on...

**Comment by jsdecena** [comment]
@muffaddal nope. Direct checkout is checking out without logging in to the application. :)

**Comment by muffaddal** [comment]
Oh cool, that means guest checkout..
