### ISSUE TITLE
Facing Issue in Installation

### ISSUE THREAD

**Issue by manishakumaribajaj** [jsdecena/laracom#23]
After Successfully migrate tables and run php artisan serve.
I am seeing this page. Can you rectify why I am seeing these issues

![image](https://user-images.githubusercontent.com/26851116/37338642-dae4eb60-26d9-11e8-8d49-e8f2d70e9561.png)

**Comment by jsdecena** [comment]
run: `php artisan migrate --seed` 😄

**Comment by manishakumaribajaj** [comment]
Thanks :) 

May I know how can I optimize its speed

**Comment by jsdecena** [comment]
There are different ways on how to optimize your laravel app. You can compile your assets and minify the html but it is not covered in the default installation of this app. 😄 Good luck!

**Comment by manishakumaribajaj** [comment]
THanks
