### ISSUE TITLE
not issues but it is questions ?  ( Why drop index  after drop table )

### ISSUE THREAD

**Issue by Nghiait123456** [jsdecena/laracom#234]
@jsdecena
jsdecena 
in  file 2017_06_11_015526_create_categories_table.php   have code:
 public function down()
    {
        Schema::table('categories', function (Blueprint $table) {

            $sm = Schema::getConnection()->getDoctrineSchemaManager();

            $doctrineTable = $sm->listTableDetails('categories');

            if ($doctrineTable->hasIndex('categories__lft__rgt_parent_id_index')) 
            {
                $table->dropIndex('categories__lft__rgt_parent_id_index');
            }

        });

        Schema::dropIfExists('categories');
    }

I know when deleting a table, the index also deletes (in mysql)
I'm curious why you deleted the index before the drop table,
If you can please help me, thank you very much for you and for this source code

**Comment by jsdecena** [comment]
In other database type, I just cannot remember which one but maybe sqlite, you must drop it before you can completely drop the whole table.
