### ISSUE TITLE
Stripe Intergration

### ISSUE THREAD

**Issue by rizdem** [jsdecena/laracom#24]
Hi love your template. Do you have any intention on adding stripe as a payment gateway? Paypal in the UK use a different api system for online payments. and I can't set it up.

Thanks

**Comment by jsdecena** [comment]
We could definitely do that, will put that in the pipeline 😄

**Comment by rizdem** [comment]
thank you.

**Comment by m2ura** [comment]
And please add Instant Electronic Fund Transfer Payment Method too.

**Comment by jsdecena** [comment]
@m2ura This is laravel, you can contribute to that as a package :)

**Comment by jsdecena** [comment]
@rizdem I have integrated already the **Stripe** payment with the version [v1.3.1](https://github.com/jsdecena/laracom/tree/v1.3.1)
