### ISSUE TITLE
Laravel version update

### ISSUE THREAD

**Issue by sanal2net** [jsdecena/laracom#241]
Current laravel version is 5.7. Is it possible to update to laravel 7?

**Comment by jsdecena** [comment]
@sanal2net Can make a PR?

**Comment by humble92** [comment]
How about the version of Laravel 6 LT version? Do you have plan to work for that?

**Comment by tecsanal** [comment]
After updating the code, I am still getting Laravel 5.7. Have you able to update to Laravel 6? if yes, can you tell me how you did it?

**Comment by humble92** [comment]
I had the same problem. Do you have any idea to go forward Laravel 6? I think I did the same thing you did.

**Comment by jsdecena** [comment]
I will find time to upgrade the version within the week. :)

**Comment by jsdecena** [comment]
> I will find time to upgrade the version within the week. :)

Just found out that the shoppingcart I am using has not been update since L5.x, I need to fork that package and make it compatible to the recent version of laravel which may take more time.

**Comment by humble92** [comment]
Thanks for your help.

**Comment by tecsanal** [comment]
Is there any progress regarding the up-gradation process? 

The shopping cart( gloudemans/shoppingcart ) you are using has not been upgraded yet, can you use the below link as an alternative method for the up-gradation process?

[](https://github.com/olimortimer/LaravelShoppingcart)

**Comment by jsdecena** [comment]
I tried but the package for the cart is main blocker. sorry. closing this for now.

**Comment by humble92** [comment]
No apologies. Thanks.

2021년 4월 14일 (수) 오후 9:10, Jeff Simons Decena ***@***.***>님이
작성:
