### ISSUE TITLE
An error will occur if a character string is entered in quantity and added to the cart.

### ISSUE THREAD

**Issue by kazuyoshi-tech** [jsdecena/laracom#242]
forgot to apply validation with formRequest

**Comment by jsdecena** [comment]
@kazuyoshi-tech yup, can you make a PR that will have the qty as integer on the validation?

**Comment by kazuyoshi-tech** [comment]
@jsdecena of course, since there was a part where an error occurred when entering a negative value or character string in both front and admin, I will fix some formRequest.

I'll make a PR in the next few days!
