### ISSUE TITLE
Subcategories display on category sidebar even though none are set for that category

### ISSUE THREAD

**Issue by iammikek** [jsdecena/laracom#245]
If I add subcategories within a parent category, I see these in the sidebar for any category even though they haven't been set for that category

steps to reproduce:

1. visit http://laracom.test/admin/categories/create
2. create new category and assign its parent to 'Gear'
3. add image and press save

4. visit http://laracom.test/category/nursery
5. subcategories for gear section is visible.

![Screenshot 2020-10-14 at 20 58 54](https://user-images.githubusercontent.com/94362/96039158-2415f480-0e60-11eb-9ef6-989d40eec111.png)
![Screenshot 2020-10-14 at 20 58 40](https://user-images.githubusercontent.com/94362/96039164-25472180-0e60-11eb-8c1c-224624cedf8c.png)

Expected behaviour:

1. visit http://laracom.test/category/nursery
2. no subcategories are visible.

**Comment by jsdecena** [comment]
@iammikek yes

**Comment by iammikek** [comment]
@jsdecena can I check with you what your expected behaviour is for the top menu, that appears to the left of the search bar on the top menu. 

Currently its displaying all sub categories. 
![Screenshot 2020-10-16 at 19 18 59](https://user-images.githubusercontent.com/94362/96294606-8ac41b00-0fe4-11eb-8409-bc2da8b5be37.png)

Are you expecting to drill down from top level categories?

**Comment by iammikek** [comment]
@jsdecena would you be able to comment on how you have planned your navigation?

I would suggest the following:

Top navigation - shows clickable links to top level categories, When you hover over them, you should see drop down of all subcategories and these are clickable.

Side navigation - displays when you enter a category, Shows all child categories right the way up to their parent:
Eg
```
Top Level Category
- Category 1
-- Category 1 Subcategory 1
-- Category 1 Subcategory 2
-- Category 1 Subcategory 3
- Category 2
-- Category 2 Subcategory 1
-- Category 2 Subcategory 2
-- Category 2 Subcategory 3
- Category 3
-- Category 3 Subcategory 1
-- Category 3 Subcategory 2
-- Category 3 Subcategory 3
```

the category you are in is highlighted in the menu.

**Comment by jsdecena** [comment]
@iammikek it's nice but if it becomes bigger it will not fit on the top navigation

**Comment by iammikek** [comment]
@jsdecena how do you think we could address the top menu issue? 

The issue with having too many categories and the menu starting to wrap is a problem with horizontal menus in general. The only way to mitigate this is to be sparing with top level categories.

Do you have any wireframes from when it was initially designed?

**Comment by jsdecena** [comment]
this is too long already. this will depend on your design. closing now :)

**Comment by iammikek** [comment]
@jsdecena did you have any original wireframes you could share?

**Comment by jsdecena** [comment]
@iammikek there are so many free stuff now over the net. You can check in: https://cssauthor.com/e-commerce-website-templates/ :)

**Comment by iammikek** [comment]
@jsdecena thanks. I was hoping to help you build out the functionality you'd originally planned for this project, which I assume you built with an original plan in mind.

My plan was to collaborate with you to help realise your original functionality, but if thats not something you're interested in we'll close this branch down.
