### ISSUE TITLE
post method  does not exist

### ISSUE THREAD

**Issue by MehdiElMellali** [jsdecena/laracom#254]
i try to login or register but i have same message problem :
```
 * @param  string  $subClass
     * @return array
     */
    public static function fromAction(array $action, $subClass = null)
    {
        $parameters = is_string($action['uses'])
                        ? static::fromClassMethodString($action['uses'])
                        : (new ReflectionFunction($action['uses']))->getParameters();
 
        return is_null($subClass) ? $parameters : array_filter($parameters, function ($p) use ($subClass) {
            return $p->getClass() && $p->getClass()->isSubclassOf($subClass);
        });
    }
```

###### Class App\Shop\Admins\Requests\LoginRequest does not exist

**Comment by leor-w** [comment]
I also encountered this problem. I used the code of Tag V1.6.0, but I did not find the directory app/Shop/Admin in the code, which was caused by missing this part of the code. I wonder where I can find the missing code

**Comment by jsdecena** [comment]
I just tried and I can't replicate this. Are you running it on docker?
