### ISSUE TITLE
Add to cart not showing

### ISSUE THREAD

**Issue by cruzerblade95** [jsdecena/laracom#257]
Hi, I just installed your project in my laptop and I just have a slight problem regarding add to cart. When I click add to cart button at the top and it shows Courier not found error. What is the solutions for this problems. Thank you.
![Screenshot (1)](https://user-images.githubusercontent.com/46733757/104829560-15503b00-58b0-11eb-9beb-fd438d0ca936.png)

**Comment by jsdecena** [comment]
have you run the seeder? @cruzerblade95
