### ISSUE TITLE
Namespace bugs

### ISSUE THREAD

**Issue by dev-ishantripathi** [jsdecena/laracom#260]
There seem to be a couple of namespace issues when opening admin dashboard links. One of the screenshots is attached below. I am attaching one of such case as I explore more I see it a lot of places. Such as LoginRequest Class

![image](https://user-images.githubusercontent.com/79321392/115967167-a5a4b880-a54e-11eb-87b5-6a292d6219bc.png)

**Comment by jsdecena** [comment]
Any replication steps? @dev-ishantripathi

**Comment by viktormaar** [comment]
I append my issue here, looks related. Also noticed some namespace bugs with a newly installed one.
Version 1.6.2
PHP 7.3
Steps to reproduce:
1) Install Laracom according the documentation
2) Migrate & seed
3) Go to `/admin` and perform a login
4) Whoops error:

> ReflectionException
> Class App\Shop\Admins\Requests\LoginRequest does not exist

A hotfix is to search for `App\Shop\Admins` in the whole project and replace all instances to `App\Shop\Employees`.
BTW I am planning to make a PR for this anyways.

**Comment by viktormaar** [comment]
PR added: https://github.com/jsdecena/laracom/pull/262
I could not reproduce issue from @dev-ishantripathi. `CourierRepository` namespacing looks good, admin functions works.
