### ISSUE TITLE
Error on search (confirmation needed)

### ISSUE THREAD

**Issue by viktormaar** [jsdecena/laracom#264]
Note: This issue is probably related to the different MySQL version and may not affect others. Tested on `10.5.5-MariaDB Homebrew`. Confirmation needed if the issue is reproducable on other configurations.

I got an Illuminate\Database\QueryException error on a frontend search:
<img width="1907" alt="search_error" src="https://user-images.githubusercontent.com/29245960/120545531-0f866c80-c3ef-11eb-924f-0af50688d51f.png">

Steps to reproduce:
1) Fresh install and seed a Laracom project
2) Create a product on the backend (to ensure that you can except a valid result)
3) Search for the product name on the frontend
4) See error

The issue can be fixed by setting the `'strict' => false` in `config/database.php` file in the `connections[mysql]` section

**Comment by jsdecena** [comment]
nice! thanks for that!
