### ISSUE TITLE
Launched Laracom on Laravel 8 🎉 

### ISSUE THREAD

**Issue by jsdecena** [jsdecena/laracom#266]
Initial move to laravel 8: https://github.com/jsdecena/laracom/releases/tag/v2.0.0

If you are not using the docker environment, make sure your local machine is compatible with https://laravel.com/docs/8.x/installation

If there are issues, comment below :) Thanks!

**Comment by SemihGursoy** [comment]
Hi @jsdecena, the documentation link is not working.

**Comment by jsdecena** [comment]
> Hi @jsdecena, the documentation link is not working.

sorry. will spin another server for it.

**Comment by jsdecena** [comment]
@SemihGursoy here's the link: https://jsdecena.github.io/laracom/
