### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by ustabasiibrahim** [jsdecena/laracom#270]
Hi,

I got the project up and running through Docker. I get this error when I want to add products from the admin panel. When sending a request, there are usually 3 pictures in it.

how can i solve this problem?

![image](https://user-images.githubusercontent.com/14348709/133944720-8c7a4f45-fd29-42f1-b01b-c8f3b8797ee9.png)

**Comment by jsdecena** [comment]
you need to update the ini files in https://github.com/jsdecena/laracom/blob/master/php/local.ini to suit your need.
