### ISSUE TITLE
Frontend main images

### ISSUE THREAD

**Issue by flimbo** [jsdecena/laracom#275]
Images are missing on the main page only even though a storage link was created.

Problem is in template file "product-list.blade.php"   

Quick fix in the file "\resources\views\front\products\product-list.blade.php"

change line 26 to:    <img src=" {{ asset("storage/$product->cover") }}" alt="{{ $product->name }}" class="img-bordered img-responsive">

**Comment by jsdecena** [comment]
Can you have PR for this @flimbo ?
