### ISSUE TITLE
Categories / Image remove not working

### ISSUE THREAD

**Issue by flimbo** [jsdecena/laracom#278]
function in CategoryRepository.php 

  public function deleteFile(array $file, $disk = null) : bool
    {
        return $this->update(['cover' => null]);
    }

seems that parameter $file is not passed anywhere. Plus it looks like function is only updating table  and does not provide any real delete file from filesystem.

**Comment by jsdecena** [comment]
@flimbo See https://github.com/jsdecena/laracom/commit/d90ac92cee9eaf7d715d9c11a4a2c92f6acb3feb
