### ISSUE TITLE
DB connection refused

### ISSUE THREAD

**Issue by yourNameIsGood** [jsdecena/laracom#285]
Trying to run this on mac osx m1 and having an issue as below:

```
In Connection.php line 703:

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_
  type = 'BASE TABLE')


In Connector.php line 70:

  SQLSTATE[HY000] [2002] Connection refuse
```

Have no problems with other steps.

Any clue with this one? 

Thanks in advance.

**Comment by jsdecena** [comment]
What is the content of your `.env`? Are you using docker?

**Comment by h114mx001** [comment]
Where is the `.env` file? I aam also facing with this problem.

**Comment by jsdecena** [comment]
@h114mx001 The `.env` is in the `/project` folder. If it is not there, rename the `.env.example` to just `.env` and see the values. When you do this, almost no configuration is needed and you can run the `docker-compose up -d` and everything should be working for you. Let me know if it still not working.
