### ISSUE TITLE
[2002] Connection refused

### ISSUE THREAD

**Issue by ecvii** [jsdecena/laracom#289]
Tried the installation process stated on the documentation page. But, ran into an error.
![2022-10-11_122230](https://user-images.githubusercontent.com/31363073/194996740-44adfee0-4a01-4dbe-b24d-6dd73dd64693.png)

**Comment by jsdecena** [comment]
@ecvii check your `.env` make sure it is like this.

```
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=root
DB_PASSWORD=secret
```

**Comment by ecvii** [comment]
Got it! Thanks!
