### ISSUE TITLE
Introduction to Mailhog

### ISSUE THREAD

**Issue by ysknsid25** [jsdecena/laracom#298]
GoodEvening, @jsdecena 

I would like to introduce mailhog as a means of sending mail.

For example, it will be possible to send e-mails for forgotten passwords via E2E.

I have tried it in my local environment and here is the result.
It has been verified on an Apple Silicon machine, so as soon as I can verify it on a Windows machine, I can send a pull request.

![image](https://user-images.githubusercontent.com/44870505/217672262-96939914-1260-407d-911b-ce7797d5a6ec.png)

![image](https://user-images.githubusercontent.com/44870505/217672309-47c1b053-5009-4a49-8ca3-69853c5b6d82.png)

![image](https://user-images.githubusercontent.com/44870505/217672382-f627bf1a-8405-4c6c-8c38-72291e984e7b.png)

**Comment by jsdecena** [comment]
yeah mailhog is good as I have used it before -- but others prefer mailtrap SMTP. We can add that in the docker-compose file if you need it. Currently, we just use the LOG in all the emails that are sent.

**Comment by ysknsid25** [comment]
@jsdecena 

I see

So you don't install a specific SMTP as an OSS product, and people can install their own locally as they like?
