### ISSUE TITLE
  syntax error, unexpected 'namespace' (T_NAMESPACE)

### ISSUE THREAD

**Issue by sivrenpriya** [jsdecena/laracom#7]
when we install laracom , i am getting following issues.can you help me?
C:\xampp\htdocs\development\priya>composer create-project jsdecena/laracom

In web.php line 20:

  syntax error, unexpected 'namespace' (T_NAMESPACE)

PHP Parse error:  syntax error, unexpected 'namespace' (T_NAMESPACE) in C:\xampp\htdocs\development\priya\laracom\routes\web.php on line 20
Script php artisan optimize handling the post-update-cmd event returned with error code 255

**Comment by jsdecena** [comment]
This is not suggested to be installed with XAMPP though. Try using, [Homestead](https://laravel.com/docs/5.5/homestead) or [Laravel Valet](https://laravel.com/docs/5.5/valet)
