### ISSUE TITLE
Multivendor

### ISSUE THREAD

**Issue by AhSem** [jsdecena/laracom#74]
It would be cool to have multi vendor support.

Thank you.

**Comment by AhSem** [comment]
#

**Comment by AhSem** [comment]
Hi just wondering, if I start to use Laracom now, and when multivendor support is ready, is it possible to upgrade it while maintaining the existing data?

I am thinking to deploy the current version to production, and upgrade it later when multivendor is ready.

**Comment by jsdecena** [comment]
@AhSem This is still under intensive development and I recommend to wait for the next version :) But multi-vendor may not be part.

**Comment by AhSem** [comment]
Sure, will definitely check it out later

**Comment by enricoromeo** [comment]
I'm currently working on a multi-vendor branch but is not ready for a pull request on Develop.
when this feature will be ready some corrections will be needed I guess
regards 

    Il Giovedì 5 Luglio 2018 4:07, Jeff Simons Decena <notifications@github.com> ha scritto:
 

 @AhSem This is still under intensive development and I recommend to wait for the next version :) But multi-vendor may not be part.—

**Comment by babatundeakinse** [comment]
Hi @enricoromeo ,
Just checking if the multi vendor feature is still in the works, would be interesting to see, if you need coding support on that please do let me know.

Thanks

**Comment by michael-hampton** [comment]
@AhSem Please check out my fork it includes multi vendor support
https://github.com/michael-hampton/laracom

**Comment by AhSem** [comment]
@michael-hampton, thank you, have you submitted a pull request to Laracom? would prefer to fork from Laracom to keep things at one place.
