### ISSUE TITLE
feature request : internationalization

### ISSUE THREAD

**Issue by kilejin** [jsdecena/laracom#92]
Great e-commerce solution !
It will be better if it provides locale/currency aware product title, description, price, image and etc
which is a feature in aimeos, another e-commerce solution.
I think It will be very advantageous to make international shop.

Thank you for your great job, anyway.

**Comment by jsdecena** [comment]
This is a good feature to have soon :)

**Comment by sebbaum** [comment]
There are Laravel packages that might help to maintain the language files.
Here are two of well-known developers in the Laravel community:
1. https://github.com/barryvdh/laravel-translation-manager
2. https://github.com/themsaid/laravel-langman-gui

I have no experience with either of them. 
I'll try to have a look into them and give some feedback soon.

Cheers
Sebastian

**Comment by AkkuFresh** [comment]
@jsdecena Do you plan to upgrade this genius application to Laravel 5.8?
I tried to do it, but there are too many dependencies inside.

Other, relating to Internationalization:
How to replace the MCPro component with an other suitable for other countries then your?

**Comment by jsdecena** [comment]
@AkkuFresh I am working on a packaged version of Laracom so it can just be installed on any version of Laravel.
